web_filename: output/content.html
groups:
  - name: Dennik N
    funding: https://predplatne.dennikn.sk/
    header: URLs gde?
    description: Na ...
    feeds:
      - name: ZdeNko
        description: Všetko
        feed: https://dennikn.sk/feed
        image: https://blsho.github.io/ncast/zdenko.png
        output: output/z.rss
        pub_url: https://blsho.github.io/ncast/z.rss
      - name: ZdeNko doma
        description: Slovensko
        feed: https://dennikn.sk/slovensko/feed/
        image: https://blsho.github.io/ncast/zdoma.png
        output: output/zdoma.rss
        pub_url: https://blsho.github.io/ncast/zdoma.rss
      - name: Technológie a veda
        description: ZdeNko odborník
        feed: https://dennikn.sk/veda/feed
        image: https://img.projektn.sk/wp-static/2024/07/pat-knih.png
        output: output/zodbornik.rss
        pub_url: https://blsho.github.io/ncast/zodbornik.rss
      - name: ZdeNko papá jogurt
        description: Kultúra
        feed: https://dennikn.sk/kultura/feed
        image: https://img.projektn.sk/wp-static/2024/07/highfive.png
        output: output/zpapajogurt.rss
        pub_url: https://blsho.github.io/ncast/zpapajogurt.rss
      - name: ZdeNko tipér
        description: Šport
        feed: https://dennikn.sk/sport/feed
        image: https://img.projektn.sk/wp-static/2025/04/Poradna-o-tele-2-1.png
        output: output/ztiper.rss
        pub_url: https://blsho.github.io/ncast/ztiper.rss
      - name: ZdeNko v krmčme
        description: Komentáre
        feed: https://dennikn.sk/komentare/feed
        image: https://blsho.github.io/ncast/zvkrcme.png
        output: output/zvkrcme.rss
        pub_url: https://blsho.github.io/ncast/zvkrcme.rss
      - name: ZdeNko vonka
        description: Svet
        feed: https://dennikn.sk/svet/feed
        image: https://img.projektn.sk/wp-static/2025/03/trumpov-svet.png
        output: output/zvonka.rss
        pub_url: https://blsho.github.io/ncast/zvonka.rss
      - name: ZdeNko v práci
        description: Ekonomika
        feed: https://dennikn.sk/ekonomika/feed
        image: https://e.dennikn.sk/wp-content/themes/dn-3-sk/build/assets/e.svg
        output: output/zvpraci.rss
        pub_url: https://blsho.github.io/ncast/zvpraci.rss
      - name: ZdeNko a ZdeNka
        description: Rodina
        feed: https://dennikn.sk/rodina-a-vztahy/feed
        image: https://img.projektn.sk/wp-static/2024/07/psychologicka-poradna.png
        output: output/zzdenka.rss
        pub_url: https://blsho.github.io/ncast/zzdenka.rss
      - name: ZdeNko na cige
        description: Zdravie
        feed: https://dennikn.sk/zdravie/feed
        image: https://blsho.github.io/ncast/zdenko.png
        output: output/znacige.rss
        pub_url: https://blsho.github.io/ncast/znacige.rss
      - name: ZdeNko a Peťka
        description: Petra Procházková
        feed: https://dennikn.sk/autor/petra-prochazkova/feed/
        image: https://img.projektn.sk/wp-static/2024/08/prochazkova-petra.jpg
        output: output/zpetka.rss
        pub_url: https://blsho.github.io/ncast/zpetka.rss
      - name: ZdenKo a Timko
        description: Timothy Snyder
        feed: https://dennikn.sk/autor/timothy-snyder/feed/
        image: https://img.projektn.sk/wp-static/2015/06/I56A8343.jpg
        output: output/ztimko.rss
        pub_url: https://blsho.github.io/ncast/ztimko.rss
      - name: ZdeNko v zámorí
        description: Trumpov svet
        feed: https://dennikn.sk/tema/trumpov-svet/feed/
        image: https://img.projektn.sk/wp-static/2025/03/trumpov-svet.png
        output: output/ztrump.rss
        pub_url: https://blsho.github.io/ncast/ztrump.rss
      - name: ZdeNko a Janka
        description: Jana Ciglerová
        feed: https://dennikn.sk/autor/jana-ciglerova/feed/
        image: https://img.projektn.sk/wp-static/2024/08/jana-foto.jpg
        output: output/zjanka.rss
        pub_url: https://blsho.github.io/ncast/zjanka.rss
      - name: V ZdeNkovej kebuli
        description: Duševné zdravie
        feed: https://dennikn.sk/tema/dusevne-zdravie/feed
        image: https://img.projektn.sk/wp-static/2024/07/psychologicka-poradna.png
        output: output/zkebuli.rss
        pub_url: https://blsho.github.io/ncast/zkebuli.rss
      - name: ZdeNko minus Audio N
        description: Vsetko bez toho, co nahraval clovek (je to asi rozhovor, ktory asi najdes sucastou bezneho podcastu)
        feed: https://dennikn.sk/feed
        image: https://blsho.github.io/ncast/zdenko.png
        output: output/znoaudio.rss
        pub_url: https://blsho.github.io/ncast/znoaudio.rss
        exclude:
          - Audio N
      - name: Zdenko bije Vladka
        description: Vývoj bojov
        feed: https://dennikn.sk/tema/vyvoj-vojny-na-ukrajine/feed
        image: https://img.projektn.sk/wp-static/2024/07/vyvoj-bojov.png
        output: output/zvladko.rss
        pub_url: https://blsho.github.io/ncast/zvladko.rss
      - name: Zdenko a Ivko
        description: Ivan Mikloš
        feed: https://dennikn.sk/autor/ivan-miklos/feed/
        image: https://img.projektn.sk/wp-static/2022/03/pjimage-2-1-1.jpg
        output: output/zivko.rss
        pub_url: https://blsho.github.io/ncast/zivko.rss
      - name: Zdenko a Romancov
        description: Michael Romancov
        feed: https://dennikn.sk/autor/michael-romancov/feed/
        image: https://img.projektn.sk/wp-static/2017/04/Romancov-zdrojANTECOM-e1591952168225.jpg
        output: output/zromancov.rss
        pub_url: https://blsho.github.io/ncast/zromancov.rss
      - name: ZdeNko budí respekt
        description: Respekt
        feed: https://dennikn.sk/autor/respekt/feed/
        image: https://img.projektn.sk/wp-static/2023/12/channels4profile-2-2.jpg
        output: output/zrespekt.rss
        pub_url: https://blsho.github.io/ncast/zrespekt.rss
      - name: ZdeNLko sadí tulipány
        description: Čo sa deje v Holandsku
        feed: https://dennikn.sk/feed/?s=holand
        image: https://blsho.github.io/ncast/zdeNLko.png
        output: output/zholand.rss
        pub_url: https://blsho.github.io/ncast/zholand.rss
  - name: Denik N
    funding: https://predplatne.denikn.cz/
    header: A helé
    description: Tady...
    feeds:
      - name: ZděNko
        description: Všechno
        feed: https://denikn.cz/feed
        image: https://blsho.github.io/ncast/zcz.png
        output: output/zcz.rss
        pub_url: https://blsho.github.io/ncast/zcz.rss
      - name: ZděNko doma
        description: Česko
        feed: https://denikn.cz/cesko/feed/
        image: https://blsho.github.io/ncast/zcz.png
        output: output/zczdoma.rss
        pub_url: https://blsho.github.io/ncast/zczdoma.rss
      - name: ZděNko vonka
        description: Svět
        feed: https://denikn.cz/svet/feed
        image: https://blsho.github.io/ncast/zcz.png
        output: output/zczvonka.rss
        pub_url: https://blsho.github.io/ncast/zczvonka.rss
      - name: ZděNko v práci
        description: Ekonomika
        feed: https://denikn.cz/ekonomika/feed
        image: https://blsho.github.io/ncast/zcz.png
        output: output/zczvpraci.rss
        pub_url: https://blsho.github.io/ncast/zczvpraci.rss
      - name: ZděNko v hospode
        description: Komentare
        feed: https://denikn.cz/nazory/feed
        image: https://blsho.github.io/ncast/zcz.png
        output: output/zczvkrcme.rss
        pub_url: https://blsho.github.io/ncast/zczvkrcme.rss
      - name: ZděNko papá jogurt
        description: Kultúra
        feed: https://denikn.cz/kultura/feed
        image: https://blsho.github.io/ncast/zcz.png
        output: output/zczpapajogurt.rss
        pub_url: https://blsho.github.io/ncast/zczpapajogurt.rss
      - name: ZděNko odborník
        description: Technológie a veda
        feed: https://denikn.cz/veda/feed
        image: https://blsho.github.io/ncast/zcz.png
        output: output/zczodbornik.rss
        pub_url: https://blsho.github.io/ncast/zczodbornik.rss
      - name: ZděNko tipér
        description: Sport
        feed: https://denikn.cz/sport/feed
        image: https://blsho.github.io/ncast/zcz.png
        output: output/zcztiper.rss
        pub_url: https://blsho.github.io/ncast/zcztiper.rss
      - name: ZděNko havo
        description: Vrtěti psem
        feed: https://denikn.cz/podcast-vrtetipsem/feed
        image: https://img.novydenik.com/wp-static/2025/05/Vrtetitipsem-logo-mini.png
        output: output/zczhavo.rss
        pub_url: https://blsho.github.io/ncast/zczhavo.rss
      - name: ZděNko a Romancov
        description: Romancov & spol.
        feed: https://denikn.cz/podcast-romancovaspol/feed
        image: https://img.novydenik.com/wp-static/2023/11/romancov-a-spol-OBR.jpg
        output: output/zczromancov.rss
        pub_url: https://blsho.github.io/ncast/zczromancov.rss
      - name: ZděNko v studiu
        description: Studio N
        feed: https://denikn.cz/podcast-studio-n/feed
        image: https://img.novydenik.com/wp-static/2024/08/StudioN-logo.png
        output: output/zczstudio.rss
        pub_url: https://blsho.github.io/ncast/zczstudio.rss
      - name: ZděNko kričí fuck yeah!
        description: Amerika bejby
        feed: https://denikn.cz/podcast-amerikabejby/feed
        image: https://img.novydenik.com/wp-static/2025/10/americky-podcast-ikona.png
        output: output/zczfckyeah.rss
        pub_url: https://blsho.github.io/ncast/zczfckyeah.rss
